# A generic, single database configuration.

[alembic]

# Path to migration scripts
script_location = %(here)s/alembic

# Database URL
#
# The actual DATABASE_URL is loaded from .env
# by alembic/env.py.
sqlalchemy.url =


# ============================================================
# POST WRITE HOOKS
# ============================================================

# post_write_hooks defines scripts or Python functions that are
# run on newly generated revision files.

# Uncomment if you want code formatting/linting later.
#
# format using "black" - use the console_scripts runner,
# default options
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME


# ============================================================
# LOGGING
# ============================================================

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic


[logger_root]
level = WARNING
handlers = console
qualname =


[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine


[logger_alembic]
level = INFO
handlers =
qualname = alembic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S